### ISSUE TITLE
Fix Our Conversation Series

### ISSUE THREAD

**Issue by yashanand1910** [yashanand1910/entrejourn.in#21]
The current videos that we have are not from the conversation series. Either we change the title OR have the series – “Millennial entrepreneurs” replace the current videos.

**Comment by Rubina110622** [comment]
1. The first video on this section is blurry. Can that be fixed?

**Comment by yashanand1910** [comment]
> 1. The first video on this section is blurry. Can that be fixed?

@Rubina110622 I have improved the quality of the image, you can check now. This is the maximum quality we can get since YouTube is only giving us 'thumbnail' images and they are usually small.

**Comment by Rubina110622** [comment]
@yashanand1910 it has become better, but then I guess there's not much we can do to improve the quality. Is there anything we need to bear in mind for the future to avoid such cases?

**Comment by yashanand1910** [comment]
> @yashanand1910 it has become better, but then I guess there's not much we can do to improve the quality. Is there anything we need to bear in mind for the future to avoid such cases?

No, unfortunately we cannot avoid this. The reason YouTube stores small thumbnails is for only one purpose - when you're scrolling through YouTube, the list of videos have a thumbnail on it and you can see how small it is.
