### ISSUE TITLE
Create Meet the Team page under About

### ISSUE THREAD

**Issue by yashanand1910** [yashanand1910/entrejourn.in#28]
Pls let us know if you need better quality photos.
We liked these formats, depending on your time, would you be able to replicate something similar?

1. https://www.atlassian.com/company/people (We like the bold colors used but not the flashy stuff. if we could also use bold colors of our website, should you decide to do something like this)
2. https://uwginc.com/aboutus/  ( I guess for this one we need more team members )
3. 360i
4. Studio MPLS
5. AREA 17

3,4,5 are here https://amasty.com/blog/30-best-meet-the-team-pages-examples-and-trends/

**Comment by Rubina110622** [comment]
1. Remove the big logo from the centre from the Blue block?
2.  Pls add these designation for the following -
     Aayushi - **Co-Creator & Strategist | Principal - HR & Operations**
     Avinash- **Co-Creator & Strategist | Principal - Networking & Community Building**
     Bhanu- **Co-Creator & Strategist | Principal - Digital Media**
     Rubina- **Co-Creator & Strategist | Principal - Website & Content**

**Comment by yashanand1910** [comment]
> * Remove the big logo from the centre from the Blue block?
> * Pls add these designation for the following -
>   Aayushi - **Co-Creator & Strategist | Principal - HR & Operations**
>   Avinash- **Co-Creator & Strategist | Principal - Networking & Community Building**
>   Bhanu- **Co-Creator & Strategist | Principal - Digital Media**
>   Rubina- **Co-Creator & Strategist | Principal - Website & Content**

Done
