### ISSUE TITLE
Create Interns & Volunteers page under About

### ISSUE THREAD

**Issue by yashanand1910** [yashanand1910/entrejourn.in#29]
- [x] - We are clubbing the Interns and Volunteers.
- [x] - There are two interns that needs to go up, pls find them in New folder
- [x] - After interns will come Volunteers- You and Anupama
- [x] - Add the text at the bottom after Volunteers
- [x] - pls let me know if you need better quality photos

**Comment by Rubina110622** [comment]
1. Replace '**college**' with '**School**' of Planning and Architecture for Samridha

**Comment by Rubina110622** [comment]
Would it be possible to reduce the space between the text and the footer? I feel its not equal.
